apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-rds-controller
  namespace: ack-system
spec:
  releaseName: rds-chart
  chart:
    spec:
      chart: rds-chart
      version: v0.1.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ack-source
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: false
    aws:
      region: us-east-2

